version: "3"
services:
  redis:
    image: "redis:6"
    container_name: "cex_redis"
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_volume:/data
  db:
    image: "postgres:13"
    container_name: "cex_db"
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_volume:/var/lib/postgresql/data
  app:
    build:
      context: ./packages/app
      dockerfile: Dockerfile
    image: cex-app:latest
    container_name: "cex_app"
    command: 'bash -c "cd ./packages/app && npm run watch:dev"'
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
      - redis
    env_file:
      - ./env/local.env
  worker:
    build:
      context: ./packages/app
      dockerfile: Dockerfile
    image: cex-app:latest
    container_name: "cex_worker"
    command: 'bash -c "cd ./packages/app && npm run watch:worker"'
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - ./env/local.env

volumes:
  redis_volume:
  db_volume:
