#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -e

yarn build || (echo "Build failed" && exit 1)

yarn format:check || (echo "Prettier format check failed, run yarn format:write" && exit 1)
